# Generated by Django 4.1.4 on 2023-06-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_api', '0006_alter_posts_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created',
            field=models.DateTimeField(default='23-06-27'),
        ),
    ]
