# Generated by Django 4.1.4 on 2023-06-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_api', '0007_alter_posts_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created',
            field=models.DateTimeField(default='27'),
        ),
    ]
