# Generated by Django 4.1.4 on 2023-07-02 16:25

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone
import video_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('video_api', '0008_alter_posts_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='posts',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='posts',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[video_api.validators.validate_file_size]),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
